import profiles from "../data/rmp-profiles.json";

const USF_PROFESSOR_SEARCH = "https://www.ratemyprofessors.com/search/professors/1262";
const PROFESSOR_PAGE = "https://www.ratemyprofessors.com/professor/";
const PLACEHOLDER = /^(staff|tba|tbd|unknown|unavailable|not available|not announced|ambiguous|n\/?a|[-–—])$/i;
const INITIAL = /^[a-z]\.?$/i;

/** Generated by scripts/match_rmp_profiles.py: "SUBJ|instructor name" -> RMP profile id. */
const PROFILE_IDS: Record<string, number> = profiles;

export interface RmpLink {
  href: string;
  kind: "profile" | "search";
}

const usableName = (instructor: string | null | undefined): string | null => {
  const raw = instructor?.trim();
  // Multiple names cannot be one professor. Commas and apostrophes are valid.
  if (!raw || PLACEHOLDER.test(raw) || /[/;|&\r\n]|\s+and\s+/i.test(raw)) return null;
  return raw.split(/\s+/).join(" ");
};

/** Same key as easy_a.rmp.matcher.link_key. */
export const rmpKey = (subject: string, name: string): string =>
  `${subject.trim().toUpperCase()}|${name.trim().split(/\s+/).join(" ").toLowerCase()}`;

// The USF schedule cuts names at 18 characters ("K. Mavridou-Hernan"); see easy_a.rmp.matcher.
const SCHEDULE_NAME_MAX = 18;

/**
 * "S. Miller" -> "Miller": the schedule's initial matches every S-named professor on RMP.
 * A cut-off surname drops its partial last piece: "K. Mavridou-Hernan" -> "Mavridou".
 */
export const lastName = (name: string): string => {
  const tokens = name.trim().split(/\s+/);
  while (tokens.length > 1 && INITIAL.test(tokens[0])) tokens.shift();
  const surname = tokens.join(" ");
  const pieces = surname.split(/[\s-]+/);
  return name.trim().split(/\s+/).join(" ").length >= SCHEDULE_NAME_MAX && pieces.length > 1
    ? pieces.slice(0, -1).join(" ")
    : surname;
};

/** That professor's own page when it was matched with confidence, otherwise a USF search. */
export function rmpLink(instructor: string | null | undefined, subject: string): RmpLink | null {
  const name = usableName(instructor);
  if (!name) return null;
  const id = PROFILE_IDS[rmpKey(subject, name)];
  if (id) return { href: `${PROFESSOR_PAGE}${id}`, kind: "profile" };
  return { href: `${USF_PROFESSOR_SEARCH}?q=${encodeURIComponent(lastName(name))}`, kind: "search" };
}
